<?php

namespace AppBundle\Repository;

/**
 * StudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
        return $this->createQueryBuilder("studio")->addSelect("editeur")->addSelect("anime")
            ->leftJoin("studio.editeur", "editeur")
            ->leftJoin("editeur.animes", "anime")
            ->getQuery()->getResult();
    }
}
